<<<<<<< HEAD
# Generated by Django 6.1 on 2026-09-09 11:47
=======
# Generated by Django 6.1 on 2026-08-18 09:04
>>>>>>> 2feabb2fe60d8c581b15980d33e09e7979fca5aa

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('employee', 'Employee'), ('customer', 'Customer')], default='customer', max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
=======
                ('role', models.CharField(choices=[('owner', 'Owner'), ('employee', 'Employee')], default='employee', max_length=20)),
>>>>>>> 2feabb2fe60d8c581b15980d33e09e7979fca5aa
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
